### ISSUE TITLE
Dataset download corrupted

### ISSUE THREAD

**Issue by maxizi** [shine636363/RGBDtracker#2]
Hello,

the download link seems to be working. However, the zip file seems to be corrupted / incomplete. 
Can you please check and provide another link for the dataset? I tried several times on several machines.

Thanks!

**Comment by shine636363** [comment]
Sorry for the late reply. Could you please try this link: https://pan.baidu.com/s/1OxprDK1hmvsXswEWMJsl4A


--------------------------------


Best regards,
Dr. Jingjing Xiao


Lecturer,  Department of Medical Engineering,
Xinqiao Hosptial, Third Military Medical University (Army Medical University), China.
(No. 183, Xinqiao Central Street, Shapingba District, Chongqing, 400037)
Honorary Research Fellow, School of Computer Science, University of Birmingham, U.K.



----- Original Message -----

**Comment by maxizi** [comment]
Thanks for taking care. The provided link is working. I was able to download and extract all files.

Thanks a lot!
