### ISSUE TITLE
Dataset download corrupted

### ISSUE THREAD

**Issue by zhengjilai** [shine636363/RGBDtracker#3]
Sorry but, the link of the dataset seems to be corrupted.  
I can only download a 4GB incomplete .zip file from that link, and the downloaded .zip file cannot be unzipped as usual. I also tried fastjar to extract that, but can only get 31 full sequences and 1 incomplete sequence. However, there should be 36 sequences in total.
From my point of view, your original .zip file may be larger than 4GB and has no problem, but the cloud disk sets a limit to the maximum size (4GB) of the downloading file. This causes the corruption.
Anyway, can you provide a link for dataset downloading? The BaiduYun link from another (closed) issue seems to be expired, as well. 
Thank you !

**Comment by shine636363** [comment]
Hi，
You can try this link. https://pan.baidu.com/s/1_NRRguzliOrgFgSFbVWZwg password：74xo
--------------------------------


Best regards,
Dr. Jingjing Xiao


Lecturer,  Department of Medical Engineering,
Xinqiao Hosptial, Third Military Medical University (Army Medical University), China.
(No. 183, Xinqiao Central Street, Shapingba District, Chongqing, 400037)
Honorary Research Fellow, School of Computer Science, University of Birmingham, U.K.



----- Original Message -----

**Comment by zhengjilai** [comment]
Thank you for your immediate reply. 
I downloaded the file from your BaiduYun Disk link, and everything seems to work now.

Thank you very much !
