### ISSUE TITLE
The link of BaiduYun Disk is  also expired.

### ISSUE THREAD

**Issue by xuefeng-zhu5** [shine636363/RGBDtracker#4]
Hello,
The link of the dataset seems to be corrupted. I can download a 4GB  .zip file from that link, but the downloaded .zip file cannot be unzipped normally.
The link of BaiduYun Disk is also expired.
Could you please share it again?
Many thanks!

**Comment by shine636363** [comment]
Please, have a go with this link.
link：https://pan.baidu.com/s/1btjHxob2umOT31vZoNYouQ code：2uij 

--------------------------------


Best regards,
Dr. Jingjing Xiao


Lecturer,  Department of Medical Engineering,
Xinqiao Hosptial, Third Military Medical University (Army Medical University), China.
(No. 183, Xinqiao Central Street, Shapingba District, Chongqing, 400037)
Honorary Research Fellow, School of Computer Science, University of Birmingham, U.K.



----- Original Message -----
From: xuefeng-zhu5 ***@***.***>
To: shine636363/RGBDtracker ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [shine636363/RGBDtracker] The link of BaiduYun Disk is  also expired. (#4)
Date: 2021-06-03 15:21


Hello,

The link of the dataset seems to be corrupted. I can download a 4GB  .zip file from that link, but the downloaded .zip file cannot be unzipped normally.

The link of BaiduYun Disk is also expired.

Could you please share it again?

Many thanks!

**Comment by xuefeng-zhu5** [comment]
The provided link is working!
Thanks a lot！

**Comment by 983632847** [comment]
Above link of Baidu Pan is expired. Could you share it again?
Thx!
